### ISSUE TITLE
Custom element doesn't exist: buien-rain-forecast.

### ISSUE THREAD

**Issue by bobkolan** [DanielsWrath/lovelace-buienradar-card#4]
I'm kind of new with custom lovelace cards. But I've added /local/buien-rain-card.js to the resources section of the lovelace control panel. When I add the card to a lovelace dashboard it gives error: "Custom element doesn't exist: buien-rain-forecast.".
What am I doing wrong?

![error](https://user-images.githubusercontent.com/80460002/112959185-75325000-9143-11eb-981a-8408584276df.PNG)

**Comment by DanielHaitink** [comment]
Only 2 months too late 😓 If you haven't already figured it out: you probably need to include the card type in the header.
I suggest adding [HACS](https://hacs.xyz/) to your home assistant. It makes it way easier to add custom plugins and cards!
